# Site settings
title: Resto-Véro
subtitle: Restauration VW 1200 standard de 1973
email: pierre.giraud@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ce blog décrit la restauration d'une coccinelle VolksWagen 1200 standard de 1973.
baseurl: "/vw-1200-73-standard" # the subpath of your site, e.g. /blog/
url: "http://pgiraud.github.io" # the base hostname & protocol for your site
twitter_username: pgira
github_username:  pgiraud

# Build settings
markdown: kramdown
